spring.application.name=servicio-rutas

server.port=8092

spring.datasource.url=jdbc:mysql://localhost:3306/rutasdb
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
